### ISSUE TITLE
Neovim だと「、。」以外の文字にジャンプしません

### ISSUE THREAD

**Issue by s-show** [juro106/ftjpn#1]
以下の設定を `init.vim` に記載してこちらのプラグインを活用しておりますが、Neovim だと `g` や `(` といった `,`、`.` 以外のキーで該当する文字にジャンプすることができません。

```
let g:ftjpn_key_list = [
    \ ['.', '。', '．'],
    \ [',', '、', '，'],
    \ ['g', 'が'],
    \ ['w', 'を'],
    \ ['(', '（', '）'],
    \ [';', '！', '？'],
    \ ['[', '「', '『', '【'],
    \ [']', '」', '』', '】'],
    \ ]
```

そのときの状況は次の動画のとおりですが、何か対策はございますでしょうか？
（キー操作をお見せするため、スクリーンキーボードを使っています。）

https://user-images.githubusercontent.com/20755159/209467066-adcb73c2-8877-4721-8c21-e5909834e11e.mp4

**Comment by juro106** [comment]
ジャンプできないのは、カーソルがある行に、"g" も "が" も無いからではないでしょうか？

**Comment by s-show** [comment]
誠に申し訳ありません。症状に応じた状況を録画すべきところ、全くそぐわない箇所を収録してしまいました。
改めまして、”が” や ”を” を含んだ行における動作状況は次のとおりですが、当初の投稿のとおり、`,` や `.` 以外のキーが反応しない状況です。

https://user-images.githubusercontent.com/20755159/209684145-aa7d4bec-27ef-479b-8115-431e8da09afc.mp4

**Comment by juro106** [comment]
こちらで素の nvim に vim-plug でこのプラグインのみをインストールして試してみましたが、期待通り動作します。
いただいた動画を見る限りおそらくデフォルトの設定しか反映されていない状態であると思われるので、もしかしたら init.vim 内での設定（g:ftjpn_key_list）の記述位置やその他のファイルの読み込み順等との兼ね合いの問題かもしれません。

**Comment by s-show** [comment]
検証していただきありがとうございました。
プラグインの設定はプラグイン毎に分割しており、それを `init.vim` でまとめて読み込むようにしていましたが、ご回答を踏まえて改めて読み込み設定を調整したところ、意図したとおりの動作になりました。
`,` や `.` の設定が意図したとおりに動いていたので、読み込み設定のエラーだと気づきませんでした。
お忙しい中ご対応していただきありがとうございました。

追伸
`,` と `.` は、設定しなくても `、` や `。` にジャンプするようデフォルトで設定されているのでしょうか？

**Comment by juro106** [comment]
解消されて良かったです。
現在、デフォルトでは以下のようになっています。
```
let g:ftjpn_key_list = [
    \ ['.', '。', '．'],
    \ [',', '、', '，'],
    \ ]
endif
```
README に書いておくか何も設定しないようにするべきでした。混乱させてしまい申し訳ありません。
